name: sqlite3_perf_flutter
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # sqlite3: ^3.3.1
  sqlite3:
    git:
      url: https://github.com/davidmartos96/sqlite3.dart
      ref: sqlite3-sqlcipher-3.3.2
      path: sqlite3
  uuid: ^4.5.3
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

hooks:
  user_defines:
    # sqlite3:
    #   source: sqlite3mc
    #   # source: sqlcipher

    # SQLCipher on Android
    sqlite3:
      source: system
      name: sqlcipher

    